root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
rules:
  react/prop-types: off
  react-hooks/exhaustive-deps: 1
overrides:
  - files: '*.{js,jsx}'
    rules:
      '@typescript-eslint/no-explicit-any': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/explicit-function-return-type': off
